spring.datasource.url=${DB_URL:jdbc:mysql://url-shortener-db.c5eq2gwm4rxe.ap-south-1.rds.amazonaws.com:3306/shortner?sslMode=VERIFY_IDENTITY&trustCertificateKeyStoreUrl=file:./rds-truststore-full.p12&trustCertificateKeyStoreType=PKCS12&trustCertificateKeyStorePassword=changeit&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:admin}
spring.datasource.password=${DB_PASSWORD:Naidu269}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect


server.port=8081
spring.jpa.show-sql=true

#  master password = Naidu269

